import papa from "papaparse";
import { type RenderSettsResults, type SaveSettsRequest } from "./Messaging";
import "./ces.t.ts"
import Logger from "./Logger.js";

export interface ProjSettings {
  active_tab: Tabs;
  data_mode: "table" | "detail";
  log_level: number;
  render_comps_folder: string;
  out_mode: OutMode;
  auto_preview: boolean;
  update_visible_col_only: boolean;
}

export interface ProjData {
  id: string;
  tmpls: TemplateData[];
  sel_tmpl: number;
}

export class SettingsHelper {
  static get DefaultProjSettings(): ProjSettings {
    return {
      active_tab: Tabs.Data,
      data_mode: "table",
      log_level: Logger.Levels.Warn,
      render_comps_folder: "~Automator Comps",
      out_mode: OutMode.Render,
      auto_preview: true,
      update_visible_col_only: true,
    };
  }

  static get DefaultProjectData(): ProjData {
    return {
      id: SettingsHelper.MakeId(),
      tmpls: [],
      sel_tmpl: -1,
    };
  }

  static MakeId(): string {
    return (
      Math.random().toString(36).substring(2, 15) +
      Math.random().toString(36).substring(2, 15)
    );
  }

  static UpdateTemplates(project: ProjData, host_templates: any[]) {
    // Ported from Settings.UpdateTemplates
    let scanned_templs: TemplateData[] = [];
    host_templates.forEach((templ) => {
      scanned_templs.push(TemplateHelper.FromJson(templ));
    });

    //Get the templates that don't exist in the current array
    let new_templs = scanned_templs.filter((s_templ) => {
      return !project.tmpls.some((old_templ) => old_templ.comp_id === s_templ.comp_id);
    });

    //Add the new templates to the current ones
    new_templs.forEach((new_templ) => {
      project.tmpls.push(new_templ);
      TemplateHelper.InitTableColumns(new_templ);
    });

    //Filter the templates that exist in the current array but not in the new one
    let old_templs = project.tmpls.filter((old_templ) => {
      return !scanned_templs.some(
        (new_templ) => new_templ.comp_id === old_templ.comp_id
      );
    });

    //Delete the old templates
    old_templs.forEach((old_templ) => {
      project.tmpls.splice(project.tmpls.indexOf(old_templ), 1);
    });

    //Find the templates that are in both
    let same_tmpls = project.tmpls.filter((old_templ) => {
      return scanned_templs.some(
        (new_templ) => new_templ.comp_id === old_templ.comp_id
      );
    });

    //Update the templates with the new data
    same_tmpls.forEach((s_tmpl) => {
      let new_templ = scanned_templs.find(
        (new_templ) => new_templ.comp_id === s_tmpl.comp_id
      );
      if (new_templ) TemplateHelper.Update(s_tmpl, new_templ);
    });
  }

  static LoadProjectData(json: any): ProjData {
    let proj: ProjData = { ...this.DefaultProjectData, ...json};
    if (!proj.id) proj.id = this.MakeId();
    
    proj.tmpls = [];
    if (json.tmpls !== undefined) {
      json.tmpls.forEach((templ: any) => {
        proj.tmpls.push(TemplateHelper.FromJson(templ));
      });
    }
    return proj;
  }
}

export interface TemplateData {
  name: string;
  comp: string;
  comp_id: number;
  active: boolean;
  columns: ColumnData[];
  rows: any[][];
  base_path: string;
  save_pattern: string;
  render_setts_templ: string;
  render_out_module_templ: string;
  generate_pattern: string;
  save_paths: string[];
  generate_names: string[];
  imported_footage_folder: string;
  gen_comps_folder: string;
  table_cols: number[];
  dep_comps: Comp[];
  dep_config: { [key: string]: DepCompSetts };
  import_file_lasts: {
    csv_folder: string | null;
    config_folder: string | null;
  };
  save_file_lasts: {
    csv_folder: string | null;
    config_folder: string | null;
  };
}

export interface ColumnData {
  cont_name: string;
  type: number;
  values: any[];
  menu_params: string[];
  alt_src_pattern: string;
  alt_src_base: string;
}

export class TemplateHelper {
  static DefaultTemplate(eg_name = "", comp_name = "", columns: ColumnData[] = []): TemplateData {
    let tmpl: TemplateData = {
      name: eg_name,
      comp: comp_name,
      comp_id: -1,
      active: true,
      columns: columns,
      rows: [],
      base_path: "",
      save_pattern: "{base_path}/{template_name}_{row_number}",
      render_setts_templ: "",
      render_out_module_templ: "",
      generate_pattern: "Generated_{increment:0000}",
      save_paths: [],
      generate_names: [],
      imported_footage_folder: "~Imported by EasyBatch",
      gen_comps_folder: "~Generated by EasyBatch",
      table_cols: [0],
      dep_comps: [],
      dep_config: {},
      import_file_lasts: {
        csv_folder: null,
        config_folder: null,
      },
      save_file_lasts: {
        csv_folder: null,
        config_folder: null,
      }
    };
    tmpl.rows = this.AsRows(tmpl);
    return tmpl;
  }

  static FromJson(json: any): TemplateData {
    let templ = Object.assign({}, this.DefaultTemplate(), json);
    templ.columns = [];

    if (json.columns !== undefined) {
      json.columns.forEach((col: any) => {
        templ.columns.push(ColumnHelper.FromJson(col));
      });
    }

    templ.rows = this.AsRows(templ);
    return templ;
  }

  static Update(tmpl: TemplateData, new_template: TemplateData) {
    tmpl.name = new_template.name;

    let new_cols = new_template.columns.filter((new_col) => {
      return !tmpl.columns.some((old_col) => old_col.cont_name === new_col.cont_name);
    });

    new_cols.forEach((new_col) => {
      let base_val = new_col.values[0] || ColumnHelper.ValidateValue("", new_col.type);

      new_col.values = new Array(tmpl.rows.length);
      tmpl.rows.forEach((row, i) => {
        new_col.values[i] = Object.assign({}, base_val);
      });

      tmpl.columns.push(new_col);
      tmpl.table_cols.push(tmpl.columns.indexOf(new_col));
    });

    let old_cols = tmpl.columns.filter((old_col) => {
      return !new_template.columns.some((new_col) => new_col.cont_name === old_col.cont_name);
    });

    old_cols.forEach((old_col) => {
      tmpl.columns.splice(tmpl.columns.indexOf(old_col), 1);
    });

    let same_cols = tmpl.columns.filter((old_col) => {
      return new_template.columns.some((new_col) => new_col.cont_name === old_col.cont_name);
    });

    same_cols.forEach((old_col) => {
      let new_col = new_template.columns.find((new_col) => new_col.cont_name === old_col.cont_name);
      if(new_col) ColumnHelper.Update(old_col, new_col);
    });

    tmpl.table_cols = tmpl.table_cols.filter((col_i) => {
      return tmpl.columns[col_i] !== undefined;
    });

    tmpl.rows = this.AsRows(tmpl);
  }

  static CleanupDependantComps(tmpl: TemplateData, all_comps: Comp[]) {
    tmpl.dep_comps = tmpl.dep_comps.filter((dc) => {
      return all_comps.some((comp) => comp.id === dc.id);
    });

    for (let i_conf in tmpl.dep_config) {
      if (!tmpl.dep_comps.some((dep_comp) => dep_comp.id === Number(i_conf))) {
        console.log("Deleting stray settings for comp", tmpl.dep_config[i_conf].id);
        delete tmpl.dep_config[i_conf];
      }
    }
  }

  static AddDependantComp(tmpl: TemplateData, comp: Comp, render_templs: RenderSettsResults) {
    let last_dep_comp_setts: DepCompSetts | null = null;
    if (tmpl.dep_comps.length > 0) {
      let last_dep_comp = tmpl.dep_comps[tmpl.dep_comps.length - 1];
      last_dep_comp_setts = tmpl.dep_config[last_dep_comp.id];
    }

    tmpl.dep_comps.push(comp);
    
    if (last_dep_comp_setts !== null) {
      tmpl.dep_config[comp.id.toString()] = {
        ...({...last_dep_comp_setts}),// clone the last settings to use as base for the new comp
        id: comp.id,
        name: comp.name,
        enabled: true,
      };
    } else {
      tmpl.dep_config[comp.id.toString()] = {
        id: comp.id,
        name: comp.name,
        enabled: true,
        render_setts_templ: render_templs.render_templs[render_templs.default_render_templ] || "",
        render_out_module_templ: render_templs.output_modules_templs[render_templs.default_output_module_templ] || "",
        save_pattern: "{base_path}/{comp_name}_{row_number}",
        save_path: "",
        save_paths: [],
      };
      this.ResolveSavePathFirstDeps(tmpl, 0);
    }
  }

  static RemoveDependantComp(tmpl: TemplateData, id: number) {
    tmpl.dep_comps = tmpl.dep_comps.filter((dc) => dc.id !== id);
    delete tmpl.dep_config[id.toString()];
  }

  static InitTableColumns(tmpl: TemplateData) {
    tmpl.table_cols = [];
    for (let col of tmpl.columns) {
      tmpl.table_cols.push(tmpl.columns.indexOf(col));
    }
    tmpl.rows = this.AsRows(tmpl);
  }

  static ResolveSavePath(tmpl: TemplateData, pattern: string, index: number, comp_name?: string): string {
    pattern = pattern.replaceAll("{base_path}", tmpl.base_path);
    pattern = pattern.replaceAll("{row_number}", index.toString());
    pattern = pattern.replaceAll("{template_name}", tmpl.name);
    pattern = pattern.replaceAll("{comp_name}", comp_name || tmpl.comp);

    pattern = pattern.replace(/\{increment:(\d.*?)\}/gm, (match, p1) => {
      let incr = parseInt(p1) + index;
      let incr_str = incr.toString().padStart(p1.length, "0");
      return incr_str;
    });

    for (let i_col in tmpl.columns) {
      pattern = pattern.replaceAll(
        `{${tmpl.columns[i_col].cont_name}}`,
        tmpl.columns[i_col].values[index]
      );
    }
    return pattern;
  }

  static ResolveSavePaths(tmpl: TemplateData) {
    tmpl.save_paths = [];
    for (let i = 0; i < tmpl.rows.length; i++) {
      tmpl.save_paths.push(this.ResolveSavePath(tmpl, tmpl.save_pattern, i));
    }
  }

  static ResolveSavePathFirstDeps(tmpl: TemplateData, index: number) {
    console.log("Resolving sample save path for dependant comps", index);

    for (let dc in tmpl.dep_config) {
      let dep_setts = tmpl.dep_config[dc];

      console.log("Resolving save path for dependant comp", dep_setts.id);
      console.log("Current save path", dep_setts.save_pattern);
      dep_setts.save_path = this.ResolveSavePath(tmpl, dep_setts.save_pattern, index, dep_setts.name);
    }
  }

  static ResolveSavePathDeps(tmpl: TemplateData) {
    console.log("Resolving save paths for all rows of dependant comps");

    for (let dc in tmpl.dep_config) {
      let dep_setts = tmpl.dep_config[dc];

      console.log("Resolving save path for dependant comp", dep_setts.id);
      console.log("Current save path", dep_setts.save_pattern);
      dep_setts.save_paths = [];

      for (let row_i = 0; row_i < tmpl.rows.length; row_i++) {
        dep_setts.save_paths.push(this.ResolveSavePath(tmpl, dep_setts.save_pattern, row_i, dep_setts.name));
      }
    }
  }

  static ResolveCompName(tmpl: TemplateData, pattern: string, index: number): string {
    pattern = pattern.replace("{row_number}", index.toString());
    pattern = pattern.replace("{template_name}", tmpl.name);

    pattern = pattern.replace(/\{increment:(\d.*?)\}/gm, (match, p1) => {
      let incr = parseInt(p1) + index;
      let incr_str = incr.toString().padStart(p1.length, "0");
      return incr_str;
    });

    for (let i_col in tmpl.columns) {
      pattern = pattern.replace(
        `{${tmpl.columns[i_col].cont_name}}`,
        tmpl.columns[i_col].values[index]
      );
    }
    return pattern;
  }

  static ResolveCompsNames(tmpl: TemplateData) {
    tmpl.generate_names = [];
    for (let i = 0; i < tmpl.rows.length; i++) {
      tmpl.generate_names.push(this.ResolveCompName(tmpl, tmpl.generate_pattern, i));
    }
  }

  static ResolveAltSrcPaths(tmpl: TemplateData) {
    this.NormalizeRows(tmpl);
    tmpl.columns.forEach((col) => {
      if (col.type === ColumnHelper.PropertyValueType.SRC_ALTERNATE) {
        ColumnHelper.ResolveColumnAltSrcPaths(col, tmpl.columns);
      }
    });
    tmpl.rows = this.AsRows(tmpl);
  }

  static ResolveAltSrcPathsRow(tmpl: TemplateData, index: number) {
    this.NormalizeRows(tmpl);
    tmpl.columns.forEach((col) => {
      if (col.type === ColumnHelper.PropertyValueType.SRC_ALTERNATE) {
        ColumnHelper.ResolveColumnAltSrcPathsRow(col, index, tmpl.columns);
      }
    });
    tmpl.rows = this.AsRows(tmpl);
  }

  static AddRow(tmpl: TemplateData) {
    let last_row = this.AsRows(tmpl).pop();

    for (let col in tmpl.columns) {
      tmpl.columns[col].values.push(
        last_row === undefined ?
          ColumnHelper.ValidateValue("", tmpl.columns[col].type)
          : ColumnHelper.ValidateValue(last_row[Number(col)], tmpl.columns[col].type)
      );
    }

    tmpl.rows = this.AsRows(tmpl);
    this.ResolveAltSrcPaths(tmpl);
  }

  static AddRowAfter(tmpl: TemplateData, index: number) {
    if (tmpl.rows.length === 0) {
      this.AddRow(tmpl);
      return;
    } else if (index < 0 || index >= tmpl.rows.length) {
      console.warn("AddRowAfter: Invalid row index", index);
      return;
    }

    let row_data = this.AsRows(tmpl)[index];

    for (let col in tmpl.columns) {
      tmpl.columns[col].values.splice(
        index + 1,
        0,
        ColumnHelper.ValidateValue(row_data[Number(col)], tmpl.columns[col].type)
      );
    }
    tmpl.rows = this.AsRows(tmpl);
    this.ResolveAltSrcPaths(tmpl);
  }

  static AddRowBefore(tmpl: TemplateData, index: number) {
    if (tmpl.rows.length === 0) {
      this.AddRow(tmpl);
      return;
    } else if (index < 0 || index >= tmpl.rows.length) {
      console.warn("AddRowBefore: Invalid row index", index);
      return;
    }

    let row_data = this.AsRows(tmpl)[index];

    for (let col in tmpl.columns) {
      tmpl.columns[col].values.splice(
        index,
        0,
        ColumnHelper.ValidateValue(row_data[Number(col)], tmpl.columns[col].type)
      );
    }

    tmpl.rows = this.AsRows(tmpl);
    this.ResolveAltSrcPaths(tmpl);
  }

  static AddColumn(tmpl: TemplateData) {
    tmpl.table_cols.push(0);
  }

  static DeleteColumn(tmpl: TemplateData, index: number) {
    tmpl.table_cols.splice(index, 1);
  }

  static DeleteRow(tmpl: TemplateData, index: number) {
    tmpl.columns.forEach((col) => {
      col.values.splice(index, 1);
    });

    this.ResolveAltSrcPaths(tmpl);
    tmpl.rows = this.AsRows(tmpl);
  }

  static AsRows(tmpl: TemplateData): any[][] {
    this.NormalizeRows(tmpl);

    let rows: any[][] = [];
    tmpl.columns.forEach((col, i) => {
      col.values.forEach((val, j) => {
        if (rows[j] === undefined) {
          rows[j] = [];
        }

        rows[j][i] = val;
      });
    });
    return rows;
  }

  static NormalizeRows(tmpl: TemplateData) {
    let max = 0;
    tmpl.columns.forEach((col) => {
      if (col.values.length > max) {
        max = col.values.length;
      }
    });

    tmpl.columns.forEach((col) => {
      while (col.values.length < max) {
        col.values.push("");
      }
    });
  }

  static UpdateRows(tmpl: TemplateData) {
    tmpl.rows = this.AsRows(tmpl);
  }

  static LoadFromCSV(tmpl: TemplateData, csv: string) {
    if (!csv || csv.trim() === "") return;

    let csv_rows = papa.parse(csv, { skipEmptyLines: true }).data as any[][];

    if (csv_rows.length === 0) return;

    let header: any[] = csv_rows.shift() as any[];

    tmpl.columns.forEach((tmpl_col) => {
      let col_i = header.indexOf(tmpl_col.cont_name);

      if (col_i < 0) return;

      tmpl_col.values = csv_rows.map((csv_row) => {
        if (csv_row[col_i] === undefined) return null;
        return ColumnHelper.ValidateValue(csv_row[col_i], tmpl_col.type);
      });
    });

    this.ResolveAltSrcPaths(tmpl);
    this.ResolveCompsNames(tmpl);
    tmpl.rows = this.AsRows(tmpl);
  }

  static MakeCSV(tmpl: TemplateData) {
    tmpl.rows = this.AsRows(tmpl);

    let cols: string[] = [];
    tmpl.columns.forEach((col) => {
      cols.push(col.cont_name);
    });

    let headers = papa.unparse([cols]);
    let csv = papa.unparse(tmpl.rows, {
      header: false,
    });

    return headers + "\r\n" + csv;
  }

  static CopyValuesFromPreview(tmpl: TemplateData, data: any, row_i: number) {
    tmpl.columns.forEach((col) => {
      let tmpl_col = data.values.find((val: any) => val.name === col.cont_name);

      if (tmpl_col !== undefined && col.type) {
        col.values[row_i] = tmpl_col.value;
      }
    });
  }
}

export class ColumnHelper {
  static get PropertyValueType() {
    return {
      COLOR: 6418,
      CUSTOM_VALUE: 6419,
      LAYER_INDEX: 6421,
      MARKER: 6420,
      MASK_INDEX: 6422,
      NO_VALUE: 6412,
      OneD: 6417,
      SHAPE: 6423,
      TEXT_DOCUMENT: 6424,
      ThreeD: 6414,
      ThreeD_SPATIAL: 6413,
      TwoD: 6416,
      TwoD_SPATIAL: 6415,
      SRC_ALTERNATE: 9001,
    };
  }

  static DefaultColumn(name = "", values: any[] = []): ColumnData {
    return {
      cont_name: name,
      type: this.PropertyValueType.TEXT_DOCUMENT,
      values: values,
      menu_params: [],
      alt_src_pattern: "",
      alt_src_base: "",
    };
  }

  static ResolveAltSrcPath(col: ColumnData, index: number, columns: ColumnData[]): string {
    let pattern = col.alt_src_pattern;

    pattern = pattern.replace("{base_path}", col.alt_src_base);
    pattern = pattern.replace("{row_number}", index.toString());

    pattern = pattern.replace(/\{increment:(\d.*?)\}/gm, (match, p1) => {
      let incr = parseInt(p1) + index;
      let incr_str = incr.toString().padStart(p1.length, "0");
      return incr_str;
    });

    for (let i_col in columns) {
      pattern = pattern.replace(
        `{${columns[i_col].cont_name}}`,
        columns[i_col].values[index]
      );
    }
    return pattern;
  }

  static ResolveColumnAltSrcPaths(col: ColumnData, columns: ColumnData[]) {
    let row_count = col.values.length;
    let old_values = col.values;

    col.values = [];
    for (let i = 0; i < row_count; i++) {
      if (typeof old_values[i] === "string" && !old_values[i].startsWith("<b>"))
        col.values.push(this.ResolveAltSrcPath(col, i, columns));
      else
        col.values.push(old_values[i]);
    }
  }

  static ResolveColumnAltSrcPathsRow(col: ColumnData, index: number, columns: ColumnData[]) {
    if (typeof col.values[index] === "string" && !col.values[index].startsWith("<b>"))
      col.values[index] = this.ResolveAltSrcPath(col, index, columns);
  }

  static FromJson(json: any): ColumnData {
    return Object.assign({}, this.DefaultColumn(), json);
  }

  static Update(col: ColumnData, new_col: ColumnData) {
    if (col.type !== new_col.type) {
      col.type = new_col.type;
      col.values = new Array(col.values.length).fill("");
    }
  }

  static ValidateValue(value: any, type: number) {
    switch (type) {
      case this.PropertyValueType.TEXT_DOCUMENT:
        if (value === undefined || typeof value !== "string") {
          value = "";
        }
        break;

      case this.PropertyValueType.OneD:
        if (value === undefined || typeof value !== "number") {
          try {
            value = parseFloat(value);
          } catch (e) {
            value = 0;
          }
        }
        break;

      case this.PropertyValueType.TwoD:
      case this.PropertyValueType.TwoD_SPATIAL:
        value = this.ValidateArray(value, 2);
        break;

      case this.PropertyValueType.ThreeD:
      case this.PropertyValueType.ThreeD_SPATIAL:
        value = this.ValidateArray(value, 3);
        break;

      case this.PropertyValueType.COLOR:
        value = this.ValidateArray(value, 4);
        break;
    }

    return value;
  }

  static ValidateArray(value: any, length: number) {
    if (value === undefined) {
      return new Array(length).fill(0);
    } else if (
      !Array.isArray(value) ||
      value.length !== length ||
      !value.every((v) => typeof v === "number")
    ) {
      if (typeof value === "string") {
        try {
          if (value !== "" && (!value.startsWith("[") && !value.endsWith("]"))) {
            value = JSON.parse("[" + value + "]");
          } else {
            value = JSON.parse(value);
          }
        } catch (e) {
          value = new Array(length).fill(0);
        }
      } else {
        value = new Array(length).fill(0);
      }
    }
    return value;
  }
}

export type Comp = {
  name: string;
  /** AE CompItem.id — always a number from the host */
  id: number;
}

/**
 * Settings for the dependant compositions
 */
export type DepCompSetts = {
  /** AE CompItem.id — always a number from the host */
  id: number;
  name: string;
  enabled: boolean;
  render_setts_templ: string;
  render_out_module_templ: string;
  save_pattern: string;
  save_path: string;
  save_paths: string[];
}

export const enum OutMode {
  Render = "render",
  Generate = "generate",
  Dependant = "dependant",
}

export const enum Tabs {
  Data = "data",
  Output = "output",
  Settings = "settings",
}


