site_name: EasyBatch Documentation
theme:
  name: material
  palette:
    scheme: slate

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide:
    - Data Tab: tab-data.md
    - Output Tab: tab-output.md
  - Known Issues: known-issues.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences