site_name: EasyBatch Documentation
theme:
  logo: assets/logo-round.png
  name: material
  language: en
  features:
    - navigation.path
    - navigation.expand
  palette:
    scheme: slate

nav:
  - Welcome: index.md
  - Getting Started: getting-started.md
  - User Guide:
    - Setup: setup.md
    - Data Tab: tab-data.md
    - Output Tab: tab-output.md
  - Known Issues: known-issues.md

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - git-revision-date-localized