site_name: EasyBatch Documentation
theme:
  name: material
  palette:
    scheme: slate

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  # - User Guide: user-guide.md
  # - Developer Guide: developer-guide.md
  # - Release Notes: release-notes.md
  # - About: about.md